### ISSUE TITLE
Multicast messages not transmitted

### ISSUE THREAD

**Issue by drl-bgch** [openwrt/odhcp6c#46]
I am running a 3.2.60 linux kernel & I find that setting the sockopt IPV6_MULTICAST_IF is required to allow the multicast messages to be transmitted via the bound interface.

Patch : 
[0001-correct-multicast-sockopt.txt](https://github.com/sbyx/odhcp6c/files/242367/0001-correct-multicast-sockopt.txt)

**Comment by themiron** [comment]
Hi, patch seems incorrect.
IPV6_MULTICAST_IF takes interface index as parameter, not boolean value, so your change hardcodes interface as 1. And, it's logically better to set outgoing mcast interface after bind to device is done.
p.s take care about author's indentation.

**Comment by drl-bgch** [comment]
Thanks for the feedback: more haste less speed!

Try this: 
[0001-correct-multicast-sockopt.txt](https://github.com/sbyx/odhcp6c/files/242601/0001-correct-multicast-sockopt.txt)

**Comment by themiron** [comment]
@drl-bgch there're ifindex and and if_index variables from above in both places, no need to dup if_nametoindex() call

**Comment by 4mig4** [comment]
Any follow up to that ?
