### ISSUE TITLE
[Feature Request] add parameter to send custom options

### ISSUE THREAD

**Issue by thperret** [openwrt/odhcp6c#48]
My ISP requires some customs (and non standards) options to be sent to get a IPv6 DHCP lease.
There is already an [issue opened](https://dev.openwrt.org/ticket/22539) in openwrt tracker that reference the same problem.
Could you implement the same command line parameter as in busybox's udhcpc (`-x` parameter)?

Thanks,
Thomas

**Comment by kgersen** [comment]
can you add UCI support for this new option ? thx

**Comment by thperret** [comment]
Implemented in 510aaf6d528210c5e8a6159f9b80b32615e88c5f
Thanks @dedeckeh
