### ISSUE TITLE
Cross compile for kind of OpenWRT can't work.

### ISSUE THREAD

**Issue by sunjingyuan** [openwrt/odhcp6c#49]
I've found a problem while I'm compile the program.
```
/tmp/XiaoMi/odhcp6c/src/script.c: In function ‘s46_to_env’:
/tmp/XiaoMi/odhcp6c/src/script.c:272:2: warning: implicit declaration of function ‘open_memstream’ [-Wimplicit-function-declaration]
  FILE *fp = open_memstream(&str, &strsize);
  ^
/tmp/XiaoMi/odhcp6c/src/script.c:272:13: warning: initialization makes pointer from integer without a cast [enabled by default]
  FILE *fp = open_memstream(&str, &strsize);
```
After I checked the lib of my uclibc in toolchain, I found that the toolchain does not have the function...
So what should I do now? The fmemopen, open_memstream, open_wmemstream can be use..Is there any other functions can replace them instead?

**Comment by sunjingyuan** [comment]
Well, I've solved the problem myself.. I recomplied the uClibc, and moved it the my openwrt...

**Comment by lperkov** [comment]
Thanks. Closing.
