### ISSUE TITLE
IPv6 ND RA update not caught

### ISSUE THREAD

**Issue by pktmania** [openwrt/odhcp6c#51]
When IPv6 ND RA has some updates for DNS server and domain name (RFC 6106), seems odhcp6c could not catch it. There is no script call with ra-updated sate for new entry with RA_DNS and RA_DOMAIN env variables.

**Comment by egorse** [comment]
@dedeckeh what's the resolution?

**Comment by dedeckeh** [comment]
@egorse See https://github.com/openwrt/odhcp6c/commit/19c64c524614ea7fdbcedcc50d6980f096ccadb9

**Comment by packetmania** [comment]
Thanks for taking care of this.
