### ISSUE TITLE
Failed to send DHCPV6 message to ff02::1:2 (Address not available)

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/odhcp6c#55]
On LEDE 17.01.4 I seem to be getting:

```
Failed to send DHCPV6 message to ff02::1:2 (Address not available)
```

trying to get a DHCPv6 lease from my provider.

This is the same configuration that worked fine on OpenWRT Chaos Calmer so I'm really not sure why that address would not be available.

Any ideas?

**Comment by dedeckeh** [comment]
Can you attach the network config you're using ?

**Comment by brianjmurrell** [comment]
```
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd31:aaaa:bbbb::/48'

config interface 'lan'
	option type 'bridge'
	option ifname 'eth1'
	option proto 'static'
	option netmask '255.255.255.0'
	option ip6assign '60'
	list ipaddr '10.75.22.253'
	list ipaddr '10.75.22.254'
	option defaultroute '0'
	option peerdns '0'
	option dns '10.75.22.247'
	option dns_search 'example.com example'

config interface 'wan0'
	option proto 'dhcp'
	option ifname 'eth0.2'
	option macaddr 'aa:bb:cc:dd:ee:ff'
	option peerdns '0'

config interface 'wan0_6'
	option proto 'dhcpv6'
	option ifname '@wan0'
	option reqaddress 'try'
	option reqprefix 'auto'
	option defaultroute '1'
	option peerdns '0'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'
	option enable_vlan4k '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option vid '1'
	option ports '0 1t 2 3 4 5 6t'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option vid '2'
	option ports '1t 6t'

config interface 'wan1'
	option ifname 'eth0.3'
	option proto 'pppoe'
	option username 'xxx'
	option password 'yyy'
	option ppp_redial 'persist'
	option peerdns '0'
	option defaultroute '0'
	option ipv6 '1'

config interface 'wan1_6'
	option ifname '@wan1'
	option proto 'dhcpv6'
	option reqaddress 'none'
	option reqprefix 'auto'
	option defaultroute '1'
	option peerdns '0'

config switch_vlan
	option device 'switch0'
	option vlan '3'
	option vid '3'
	option ports '1t 6t'

config switch_vlan
	option device 'switch0'
	option vlan '15'
	option vid '15'
	option ports '1t 6t'

config interface 'pppoe_ether'
	option ifname 'eth0.3'
	option proto 'static'
	option ipaddr '10.0.0.1'
	option netmask '255.255.255.0'
	option defaultroute '0'
	option peerdns '0'

config interface 'henet'
	option proto '6in4'
	option peeraddr '216.66.38.58'
	option ip6addr '2001:123:1c:abc::2/64'
	option ip6prefix '2001:123:1d:abc::/64'
	option tunnelid '123456'
	option username 'xxxxxxxx'
	option password 'xxxxxxx'
	option updatekey 'xxxxxxx'

config interface 'guest'
	option proto 'static'
	option netmask '255.255.255.0'
	option type 'bridge'
	option _orig_ifname 'eth0.100 radio0.network2'
	option _orig_bridge 'true'
	option ifname 'eth0.15'
```

**Comment by brianjmurrell** [comment]
Hrm.  Perhaps related, but `odhcpd` doesn't seem to be responding to router solicitation requests either:

```
$ sudo rdisc6 eth0
Soliciting ff02::2 (ff02::2) on eth0...
Timed out.
Timed out.
Timed out.
No response.
```

Definitely not _iptables_ as I have created a rule specifically and it's counters are registering the hits:

```
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   10   648 ACCEPT     all      *      *       ::/0                 ff02::2             
```

**Comment by themiron** [comment]
seems your configured ipv6 interface doesn't have ll address

**Comment by brianjmurrell** [comment]
@themiron is that in reference to the `odhcp6c` error or the `odhcpd` not responding to router solicitations?

In either case, both the interface on the router that `odhcp6c` is trying to use as well as the interface on the host that is running `rdisc6` have an addresses in the _fe80::/10_ block.  As well, the _lan_ interface on the router where the router solicitations are being received all has an address in the _fe80::/10_ block.

**Comment by dedeckeh** [comment]
A quick look to your network config does not show any obvious config issues.
Do both of the wan6 interfaces (wan0_6 and wan1_6) show this issue ?
As @themiron pointed out this trace is often triggered when there's no valid link local address in use or when no layer3 connectity is supported on the device eg due to the device being a bridge member
Can you display the output of "ip -6 addr show" to confirm you've valid link local addresses in use ?

**Comment by brianjmurrell** [comment]
> Do both of the wan6 interfaces (wan0_6 and wan1_6) show this issue ?

No, only the wan0_6 interface as you will see in the output below.

```
# ip -6 addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::1ad6:c7ff:fe8c:c116/64 scope link 
       valid_lft forever preferred_lft forever
7: br-guest: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::1ad6:c7ff:fe8c:c116/64 scope link 
       valid_lft forever preferred_lft forever
10: eth0.3@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::1ad6:c7ff:fe8c:c116/64 scope link 
       valid_lft forever preferred_lft forever
11: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::eade:27ff:fe77:771c/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever
13: 6in4-henet@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1280 state UNKNOWN qlen 1
    inet6 2001:123:1c:abc::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::43c1:d5d3/64 scope link 
       valid_lft forever preferred_lft forever
15: pppoe-wan1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 state UNKNOWN qlen 3
    inet6 2607:0000:1111:222:3333:9eb3:44f8:288f/64 scope global noprefixroute dynamic 
       valid_lft 2591840sec preferred_lft 604640sec
    inet6 fe80::d538:9eb3:44f8:288f/10 scope link 
       valid_lft forever preferred_lft forever
17: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
[delegated local ipv6 subnets redacted]
    inet6 fe80::1ad6:c7ff:fe8c:c115/64 scope link 
       valid_lft forever preferred_lft forever
25: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::1ad6:c7ff:fe8c:c113/64 scope link 
       valid_lft forever preferred_lft forever
27: wlan0-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::18d6:c7ff:fe8c:c113/64 scope link 
       valid_lft forever preferred_lft forever
28: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::1ad6:c7ff:fe8c:c114/64 scope link 
       valid_lft forever preferred_lft forever
29: wlan1-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::18d6:c7ff:fe8c:c114/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by dedeckeh** [comment]
The output confirms there's no valid link local address present for eth0.2

11: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::eade:27ff:fe77:771c/64 scope link tentative **dadfailed** 
       valid_lft forever preferred_lft forever


The duplicate address detection for fe80::eade:27ff:fe77:771c/64 has failed

**Comment by brianjmurrell** [comment]
Ahhh.  Duplicate address detection.  This is a new one on me.  I reset (down then up) the eth0.2 interface and it now seems to be getting a DHCP lease.  Thanks much for that bit of education.

**Comment by erotavlas85** [comment]
Hi,
I'm having the same problem on openWRT 18.06.1. Is it better to open a new issue?

**Comment by dedeckeh** [comment]
@erotavlas85 As mentioned here this indicates you have no link local address on your configured IPv6 interface. The reason can be that Duplicate Address Detection is failing for the link local address

**Comment by erotavlas85** [comment]
Ok, could be the ISP that does not provide IPv6?

**Comment by dedeckeh** [comment]
Can you attach the network config you're using and the output of ip -6 addr show ?

**Comment by erotavlas85** [comment]
I'm using mwan3 multi wan with load balancing

cat /etc/config/network 

```
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fde4:8dba:82e2::/48'

config interface 'self'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.255'
	option gateway '192.168.1.1'

config dsl 'dsl'
	option xfer_mode 'atm'
	option annex 'a'
	option ds_snr_offset '0'

config interface 'lan'
	option proto 'static'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option ifname 'eth0.1'
	option ipaddr '192.168.2.1'

config device 'lan_dev'
	option name 'eth0.1'
	option macaddr '34:8a:ae:89:59:c2'

config interface 'wan'
	option _orig_ifname 'ptm0'
	option _orig_bridge 'false'
	option proto 'pppoa'
	option encaps 'vc'
	option atmdev '0'
	option vci '35'
	option vpi '8'
	option username 'user@domain'
	option password 'password'
	option ipv6 'auto'
	option peerdns '0'
	option mtu '1478'
	option metric '10'
	option dns '193.138.219.228 31.171.251.118 192.71.245.208'

config device 'wan_dev'
	option macaddr '34:8a:ae:89:59:c2'
	option name 'dsl0'

config interface 'wan6'
	option ifname '@wan'
	option proto 'dhcpv6'
	option reqaddress 'try'
	option reqprefix 'auto'
	option peerdns '0'
	option dns '2a05:dfc7:5::53 2a05:dfc7:5353::53 2404:9400:3:0:216:3eff:fee0:7f69'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option vid '1'
	option ports '0 1 2 6t'

config switch_vlan
	option device 'switch0'
	option vlan '2'
	option vid '2'
	option ports '4 6t'

config interface 'openvpn'
	option proto 'none'
	option ifname 'tun0'

config interface 'wireguard'
	option proto 'wireguard'
	option listen_port '51820'
	option metric '50'
	option force_link '1'
	option private_key 'cBY2Q2vOMXQ/CLMLI83J/7x3iBm4tKRw9ppazvqI1111'
	list addresses '10.30.11.10/19'
	list addresses '2a01:b5c0:5:4100::b4c/64'

config interface 'wwan'
	option proto 'dhcp'
	option metric '20'
	option peerdns '0'
	option dns '193.138.219.228 31.171.251.118 192.71.245.208'

config interface 'wwan1'
	option proto 'dhcp'
	option metric '30'
	option peerdns '0'
	option dns '193.138.219.228 31.171.251.118 192.71.245.208'

config interface 'wwan2'
	option proto 'dhcp'
	option metric '40'
	option peerdns '0'
	option dns '193.138.219.228 31.171.251.118 192.71.245.208'

config interface 'wlan'
	option type 'bridge'
	option proto 'static'
	option igmp_snooping '1'
	option ipaddr '192.168.3.1'
	option netmask '255.255.255.0'
	option ip6assign '60'

config interface 'lan_iptv'
	option proto 'static'
	option ifname 'eth0.2'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option ipaddr '192.168.1.1'

config switch_vlan
	option device 'switch0'
	option vlan '3'
	option vid '3'
	option ports '5 6t'

config interface 'wwan3'
	option proto 'dhcp'
	option peerdns '0'
	option metric '50'
	option dns '193.138.219.228 31.171.251.118 192.71.245.208'

config interface 'lan_manager'
	option ifname 'eth0.3'
	option proto 'static'
	option ipaddr '192.168.0.1'
	option netmask '255.255.255.0'

config wireguard_wireguard
	option public_key 'ZcFmXAL9JWCQoS//5w9WRDKTzTcOlhXXNOX/8d/cSF8='
	list allowed_ips '0.0.0.0/0'
	list allowed_ips '::/0'
	option endpoint_host 'prova'
	option endpoint_port '51820'
	option persistent_keepalive '25'

```

```
ip -6 addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::9847:a8ff:fe34:8534/64 scope link 
       valid_lft forever preferred_lft forever
7: eth0.1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fde4:8dba:82e2::1/60 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::368a:aeff:fe89:59c0/64 scope link 
       valid_lft forever preferred_lft forever
8: eth0.2@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fde4:8dba:82e2:10::1/60 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::9847:a8ff:fe34:8534/64 scope link 
       valid_lft forever preferred_lft forever
9: eth0.3@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::9847:a8ff:fe34:8534/64 scope link 
       valid_lft forever preferred_lft forever
10: br-wlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fde4:8dba:82e2:20::1/60 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::368a:aeff:fe89:59c3/64 scope link 
       valid_lft forever preferred_lft forever
21: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::368a:aeff:fe89:59c3/64 scope link 
       valid_lft forever preferred_lft forever
24: ifb4pppoa-wan: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 32
    inet6 fe80::ecc1:41ff:fe08:c5d6/64 scope link 
       valid_lft forever preferred_lft forever
26: wireguard: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 state UNKNOWN qlen 1
    inet6 2a01:b5c0:5:4000::b4c/64 scope global 
       valid_lft forever preferred_lft forever
```

**Comment by dedeckeh** [comment]
Probably your ISP does not offer IPv6 support; this can be verified by checking the output of ifstatus wan.
I also observe a config issue; you cannot specify ipv6=auto and at the same time configure a wan6 interface. Setting ipv6 to auto will automatically create a wan_6 interface; if you want to configure a wan6 interface you need to set ipv6 to 1. As it stands now you have both a wan6 and wan_6 interface which is not correct.

**Comment by erotavlas85** [comment]
```
 ifstatus wan
{
	"up": true,
	"pending": false,
	"available": true,
	"autostart": true,
	"dynamic": false,
	"uptime": 20468,
	"l3_device": "pppoa-wan",
	"proto": "pppoa",
	"updated": [
		"addresses",
		"routes"
	],
	"metric": 10,
	"dns_metric": 0,
	"delegation": true,
	"ipv4-address": [
		{
			"address": "94.38.102.10",
			"mask": 32,
			"ptpaddress": "213.203.5.51"
		}
	],
	"ipv6-address": [
		
	],
	"ipv6-prefix": [
		
	],
	"ipv6-prefix-assignment": [
		
	],
	"route": [
		{
			"target": "0.0.0.0",
			"mask": 0,
			"nexthop": "213.203.5.51",
			"source": "0.0.0.0\/0"
		}
	],
	"dns-server": [
		"193.138.219.228",
		"31.171.251.118",
		"192.71.245.208"
	],
	"dns-search": [
		
	],
	"inactive": {
		"ipv4-address": [
			
		],
		"ipv6-address": [
			
		],
		"route": [
			
		],
		"dns-server": [
			"213.205.32.70",
			"8.8.8.8"
		],
		"dns-search": [
			
		]
	},
	"data": {
		
	}
}

```

I do not have wan_6. I never changed wan6 Alias Interface (DHCPv6 client) and it is the default configuration of openWRT.

```
config interface 'wan'
	option _orig_ifname 'ptm0'
	option _orig_bridge 'false'
	option proto 'pppoa'
	option encaps 'vc'
	option atmdev '0'
	option vci '35'
	option vpi '8'
	option username 'user'
	option password 'x'
	option ipv6 'auto'
	option peerdns '0'
	option mtu '1478'
	option metric '10'
	option dns '193.138.219.228 31.171.251.118 192.71.245.208'

config interface 'wan6'
	option ifname '@wan'
	option proto 'dhcpv6'
	option reqaddress 'try'
	option reqprefix 'auto'
	option peerdns '0'
	option dns '2a05:dfc7:5::53 2a05:dfc7:5353::53 2404:9400:3:0:216:3eff:fee0:7f69'

```

**Comment by dedeckeh** [comment]
Output of ifstatus wan shows your ISP is not offering IPv6 as no link local IPv6 address is negotiated during PPP setup. This explains the traces you're seeing as DHCPv6 requires a link local IPv6 address to be present.
Regarding the ipv6=auto config if you're using 18.06 this is not the default configuration anymore as ipv6 is now set to 1 (https://github.com/openwrt/openwrt/blob/master/package/base-files/files/bin/config_generate#L136)
As mentioned if ipv6 is set to auto the ppp6-up script will create a dynamic wan_6 interface (https://github.com/openwrt/openwrt/blob/master/package/network/services/ppp/files/lib/netifd/ppp6-up) which will conflict with the configured wan6 interface

**Comment by erotavlas85** [comment]
> Output of ifstatus wan shows your ISP is not offering IPv6 as no link local IPv6 address is negotiated during PPP setup. This explains the traces you're seeing as DHCPv6 requires a link local IPv6 address to be present.

So, [my hypothesis](https://github.com/openwrt/odhcp6c/issues/55#issuecomment-431643820) was right.

> 
Regarding the ipv6=auto config if you're using 18.06 this is not the default configuration anymore as ipv6 is now set to 1 (https://github.com/openwrt/openwrt/blob/master/package/base-files/files/bin/config_generate#L136)

You are right, I upgraded from 17.04 and so the configuration is not the default of 18.06.
Now, I set ipv6 to 1.

> As mentioned if ipv6 is set to auto the ppp6-up script will create a dynamic wan_6 interface (https://github.com/openwrt/openwrt/blob/master/package/network/services/ppp/files/lib/netifd/ppp6-up) which will conflict with the configured wan6 interface

Only to understand, why is wan_6 not present in `/etc/config/network`? But it is present wan6 (autoconfigured alias)?

**Comment by dedeckeh** [comment]
> > Output of ifstatus wan shows your ISP is not offering IPv6 as no link local IPv6 address is negotiated during PPP setup. This explains the traces you're seeing as DHCPv6 requires a link local IPv6 address to be present.
> 
> So, [my hypothesis](https://github.com/openwrt/odhcp6c/issues/55#issuecomment-431643820) was right.
> 
> > 
> 
> Regarding the ipv6=auto config if you're using 18.06 this is not the default configuration anymore as ipv6 is now set to 1 (https://github.com/openwrt/openwrt/blob/master/package/base-files/files/bin/config_generate#L136)
> 
> You are right, I upgraded from 17.04 and so the configuration is not the default of 18.06.
> Now, I set ipv6 to 1.
> 
> > As mentioned if ipv6 is set to auto the ppp6-up script will create a dynamic wan_6 interface (https://github.com/openwrt/openwrt/blob/master/package/network/services/ppp/files/lib/netifd/ppp6-up) which will conflict with the configured wan6 interface
> 
> Only to understand, why is wan_6 not present in `/etc/config/network`? But it is present wan6 (autoconfigured alias)?
wan_6 is a dynamic interface created by the ppp6-up script; as it's dynamic created it's not present in '/etc/config/network'. wan6 is an interface created based on uci network config

**Comment by darkrain88** [comment]
`root@Openwrt:~# ip -6 addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
10: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::2e0:4cff:fe65:2460/64 scope link
       valid_lft forever preferred_lft forever
15: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2409:8a1e:8fc0:dd60::1/60 scope global dynamic noprefixroute
       valid_lft 220517sec preferred_lft 134117sec
    inet6 fdad:d806:4d8c::1/60 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::2e0:4cff:fe65:245d/64 scope link
       valid_lft forever preferred_lft forever
22: pppoe-wan: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 state UNKNOWN                                                                            qlen 3
    inet6 2409:8a1e:8f0c::a35e/64 scope global dynamic noprefixroute                                                                      
       valid_lft 258952sec preferred_lft 172552sec
    inet6 fe80::c95a:af6b:c7ce:a35e/10 scope link
       valid_lft forever preferred_lft forever

`
`Tue Oct 30 08:38:35 2018 daemon.err odhcp6c[4986]: Failed to send DHCPV6 message to ff02::1:2 (Address not available)
Tue Oct 30 08:40:48 2018 daemon.err odhcp6c[4986]: Failed to send DHCPV6 message to ff02::1:2 (Address not available)
Tue Oct 30 08:42:51 2018 daemon.err odhcp6c[4986]: Failed to send DHCPV6 message to ff02::1:2 (Address not available)
Tue Oct 30 08:44:49 2018 daemon.err odhcp6c[4986]: Failed to send DHCPV6 message to ff02::1:2 (Address not available)`

same issue

firmware	Openwrt Koolshare mod V2.24 r9105-ddb753c54d
kernel	4.14.75

**Comment by toughdeep** [comment]
> wan_6 is a dynamic interface created by the ppp6-up script; as it's dynamic created it's not present in '/etc/config/network'. wan6 is an interface created based on uci network config

I am sorry for writing here after it was closed long ago, but I still have the issue. 

Thank you for the explanation and the hard work you all have been doing. 
Being a new user of Openwrt, I have same issue but could not find the solution for this issue explained simply. 

Finally, I am here, but still do not know what to do after reading all this bug report. My device is- linksys 32000ACM router with  OpenWrt 23.05.5 which I recently installed. 

**Could someone provide the solution from user's perspective for this issue to disable this setting?** 


` 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000 
     inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1508 state UP qlen 1024
    inet6 fe80::6238:e0ff:feb6:a180/64 scope link
       valid_lft forever preferred_lft forever

7: wan@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::6038:e0ff:feb6:a180/64 scope link
       valid_lft forever preferred_lft forever

11: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fd56:c2d6:30cb::1/60 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe80::6238:e0ff:feb6:a180/64 scope link
       valid_lft forever preferred_lft forever

12: phy0-ap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::6238:e0ff:feb6:a182/64 scope link
       valid_lft forever preferred_lft forever

13: phy1-ap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::6238:e0ff:feb6:a181/64 scope link
       valid_lft forever preferred_lft forever
`
