### ISSUE TITLE
odhcp6c with sigusr2 signal sends release but sends solicit message immediately 

### ISSUE THREAD

**Issue by mogulapranay-freescale** [openwrt/odhcp6c#58]

**Comment by dedeckeh** [comment]
That's the actual intended behavior of SIGUSR2; send a RELEASE and restart the state machine by sending SOLICIT messages

**Comment by mogulapranay-freescale** [comment]
Thanks for reply, if we want to release the IPv6 and don't send any solicit message just like ipv4 release, is there any option supports?

**Comment by mogulapranay-freescale** [comment]
yes, bring down wan6 interface will release (if not using -k option) but i need same behavior of v4 (udhcp) without interface down.

**Comment by dedeckeh** [comment]
I don't understand your use case at all ...
So you want to bring down the DHCPv6 state machine but you don't want to bring down the interface ...
This will trigger anyway the script down action which will bring down the interface in netifd
Either you've a funky requirement which you're not telling me or are you using the odhcp6c client on a non-OpenWrt environment ?

**Comment by dedeckeh** [comment]
But what's the difference by bringing down the interface via ifdown and later bring it up back again via ifup ? The client will also send a RELEASE and will start to request the IP address again when brought up.

**Comment by mogulapranay-freescale** [comment]
Almost same but instead of doing manually backend ifup and ifdown interface, want to know whether odhcp6c can handle? will close this issue

**Comment by dedeckeh** [comment]
The current implementation of odhcp6c cannot handle the udhcpc SIGUSR2 behavior

**Comment by mogulapranay-freescale** [comment]
Not an issue, need to down the interface to release ip
