### ISSUE TITLE
can odhcp6c support DHCPv6 only

### ISSUE THREAD

**Issue by yuanjianpeng** [openwrt/odhcp6c#60]
odhcp6c requires a RA address, can it support DHCPv6 address only ? I found no options to do this.

**Comment by dedeckeh** [comment]
Can you elaborate what you mean with "odhcp6c requires a RA address, can it support DHCPv6 address only" ? odhcp6c does not require a RA address nor a DHCPv6 address to be operational; it can perfectly be operational when it only receives a DHCPv6 prefix and RA messages without a prefix

**Comment by dedeckeh** [comment]
Closing as it's a duplicate of https://bugs.openwrt.org/index.php?do=details&task_id=2479
