### ISSUE TITLE
Starting odhcp6c as a daemon results in a continuously increasing recv buffer of raw sockets.

### ISSUE THREAD

**Issue by Horbivores** [openwrt/odhcp6c#79]
When starting odhcp6c as a daemon using the command "odhcp6c -s /etc/odhcp6c.script -p /var/run/eth0_odhcp6c.pid -P 0 -t 120 eth0", the DHCPv6 server sends RA packets every 10 seconds.
However, it was observed that the raw socket's receive buffer keeps increasing continuously.
After investigating the code, an error was found: the I/O signal was bound before starting the daemon, causing the daemon to not receive the I/O signal. Consequently, the raw socket's recv queue kept growing indefinitely.

I have observed that this bug seems to be persistent.

This patch is my solution, which places the initialization after creating the daemon process.

**Comment by ascendbeing** [comment]
the patch is available on this issue post: https://github.com/openwrt/openwrt/issues/14118 (they forgot to add it)
